# PowerShell Profile
# Auto-generated by dotfiles

# Import modules if available
if (Get-Module -ListAvailable -Name posh-git) {
    Import-Module posh-git
}
if (Get-Module -ListAvailable -Name Terminal-Icons) {
    Import-Module Terminal-Icons
}
if (Get-Module -ListAvailable -Name PSReadLine) {
    Import-Module PSReadLine
    Set-PSReadLineOption -PredictionSource History
    Set-PSReadLineOption -PredictionViewStyle ListView
}
if (Get-Module -ListAvailable -Name z) {
    Import-Module z
}
if (Get-Module -ListAvailable -Name PSFzf) {
    Import-Module PSFzf
}

# Aliases
Set-Alias -Name g -Value git -ErrorAction SilentlyContinue
Set-Alias -Name lg -Value lazygit -ErrorAction SilentlyContinue
Set-Alias -Name v -Value nvim -ErrorAction SilentlyContinue

# Only set these if the commands exist
if (Get-Command eza -ErrorAction SilentlyContinue) {
    function ll { eza -la --icons }
    function la { eza -a --icons }
    function lt { eza --tree --level=2 --icons }
}

# Starship prompt
if (Get-Command starship -ErrorAction SilentlyContinue) {
    Invoke-Expression (&starship init powershell)
}

# Zoxide
if (Get-Command zoxide -ErrorAction SilentlyContinue) {
    Invoke-Expression (& { (zoxide init powershell | Out-String) })
}

# Atuin
if (Get-Command atuin -ErrorAction SilentlyContinue) {
    Invoke-Expression (& { (atuin init powershell | Out-String) })
}

# Helper functions
function mkcd {
    param($Path)
    New-Item -ItemType Directory -Force -Path $Path | Out-Null
    Set-Location $Path
}

function which {
    param($Command)
    (Get-Command $Command -ErrorAction SilentlyContinue).Source
}

function reload {
    . $PROFILE
}

# Load local profile if it exists
if (Test-Path "$HOME\.config\powershell\profile.local.ps1") {
    . "$HOME\.config\powershell\profile.local.ps1"
}
