# LazyGit configuration
gui:
  showIcons: true
  nerdFontsVersion: "3"
  showRandomTip: false
  border: "rounded"
  filterMode: "fuzzy"

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  autoFetch: true
  autoRefresh: true

os:
  editPreset: "nvim"

reporting: "off"
disableStartupPopup: true
