gui:
  showIcons: true
  nerdFontsVersion: "3"
  showRandomTip: false
  border: rounded
  filterMode: fuzzy

git:
  paging:
    pager: delta --dark --paging=never
  autoFetch: true
  autoRefresh: true

os:
  editPreset: nvim

reporting: "off"
disableStartupPopup: true
